export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const DISPLAY_ZIPCODE = "DISPLAY_ZIPCODE";
export const LOGOUT = "LOGOUT";
export const SAVE_MATCHED_USERS = "SAVE_MATCHED_USERS";
export const STORE_CONTACTS_ARRAY = "STORE_CONTACTS_ARRAY";
export const SET_ACTIVE_THREAD = "SET_ACTIVE_THREAD";